// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: protoapi.proto

package protoapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RandomParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seed          int64                  `protobuf:"varint,1,opt,name=Seed,proto3" json:"Seed,omitempty"`
	Place         int64                  `protobuf:"varint,2,opt,name=Place,proto3" json:"Place,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandomParams) Reset() {
	*x = RandomParams{}
	mi := &file_protoapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomParams) ProtoMessage() {}

func (x *RandomParams) ProtoReflect() protoreflect.Message {
	mi := &file_protoapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomParams.ProtoReflect.Descriptor instead.
func (*RandomParams) Descriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{0}
}

func (x *RandomParams) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *RandomParams) GetPlace() int64 {
	if x != nil {
		return x.Place
	}
	return 0
}

type RandomInt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandomInt) Reset() {
	*x = RandomInt{}
	mi := &file_protoapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomInt) ProtoMessage() {}

func (x *RandomInt) ProtoReflect() protoreflect.Message {
	mi := &file_protoapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomInt.ProtoReflect.Descriptor instead.
func (*RandomInt) Descriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{1}
}

func (x *RandomInt) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type DateTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateTime) Reset() {
	*x = DateTime{}
	mi := &file_protoapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateTime) ProtoMessage() {}

func (x *DateTime) ProtoReflect() protoreflect.Message {
	mi := &file_protoapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateTime.ProtoReflect.Descriptor instead.
func (*DateTime) Descriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{2}
}

func (x *DateTime) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type RequestDateTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestDateTime) Reset() {
	*x = RequestDateTime{}
	mi := &file_protoapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestDateTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDateTime) ProtoMessage() {}

func (x *RequestDateTime) ProtoReflect() protoreflect.Message {
	mi := &file_protoapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDateTime.ProtoReflect.Descriptor instead.
func (*RequestDateTime) Descriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{3}
}

func (x *RequestDateTime) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type RequestPass struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seed          int64                  `protobuf:"varint,1,opt,name=Seed,proto3" json:"Seed,omitempty"`
	Length        int64                  `protobuf:"varint,8,opt,name=Length,proto3" json:"Length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPass) Reset() {
	*x = RequestPass{}
	mi := &file_protoapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPass) ProtoMessage() {}

func (x *RequestPass) ProtoReflect() protoreflect.Message {
	mi := &file_protoapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPass.ProtoReflect.Descriptor instead.
func (*RequestPass) Descriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{4}
}

func (x *RequestPass) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *RequestPass) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type RandomPass struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandomPass) Reset() {
	*x = RandomPass{}
	mi := &file_protoapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomPass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomPass) ProtoMessage() {}

func (x *RandomPass) ProtoReflect() protoreflect.Message {
	mi := &file_protoapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomPass.ProtoReflect.Descriptor instead.
func (*RandomPass) Descriptor() ([]byte, []int) {
	return file_protoapi_proto_rawDescGZIP(), []int{5}
}

func (x *RandomPass) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_protoapi_proto protoreflect.FileDescriptor

const file_protoapi_proto_rawDesc = "" +
	"\n" +
	"\x0eprotoapi.proto\"8\n" +
	"\fRandomParams\x12\x12\n" +
	"\x04Seed\x18\x01 \x01(\x03R\x04Seed\x12\x14\n" +
	"\x05Place\x18\x02 \x01(\x03R\x05Place\"!\n" +
	"\tRandomInt\x12\x14\n" +
	"\x05Value\x18\x01 \x01(\x03R\x05Value\" \n" +
	"\bDateTime\x12\x14\n" +
	"\x05Value\x18\x01 \x01(\tR\x05Value\"'\n" +
	"\x0fRequestDateTime\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\tR\x05Value\"9\n" +
	"\vRequestPass\x12\x12\n" +
	"\x04Seed\x18\x01 \x01(\x03R\x04Seed\x12\x16\n" +
	"\x06Length\x18\b \x01(\x03R\x06Length\"(\n" +
	"\n" +
	"RandomPass\x12\x1a\n" +
	"\bPassword\x18\x01 \x01(\tR\bPassword2\x84\x01\n" +
	"\x06Random\x12&\n" +
	"\aGetDate\x12\x10.RequestDateTime\x1a\t.DateTime\x12&\n" +
	"\tGetRandom\x12\r.RandomParams\x1a\n" +
	".RandomInt\x12*\n" +
	"\rGetRandomPass\x12\f.RequestPass\x1a\v.RandomPassB\rZ\v./;protoapib\x06proto3"

var (
	file_protoapi_proto_rawDescOnce sync.Once
	file_protoapi_proto_rawDescData []byte
)

func file_protoapi_proto_rawDescGZIP() []byte {
	file_protoapi_proto_rawDescOnce.Do(func() {
		file_protoapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protoapi_proto_rawDesc), len(file_protoapi_proto_rawDesc)))
	})
	return file_protoapi_proto_rawDescData
}

var file_protoapi_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protoapi_proto_goTypes = []any{
	(*RandomParams)(nil),    // 0: RandomParams
	(*RandomInt)(nil),       // 1: RandomInt
	(*DateTime)(nil),        // 2: DateTime
	(*RequestDateTime)(nil), // 3: RequestDateTime
	(*RequestPass)(nil),     // 4: RequestPass
	(*RandomPass)(nil),      // 5: RandomPass
}
var file_protoapi_proto_depIdxs = []int32{
	3, // 0: Random.GetDate:input_type -> RequestDateTime
	0, // 1: Random.GetRandom:input_type -> RandomParams
	4, // 2: Random.GetRandomPass:input_type -> RequestPass
	2, // 3: Random.GetDate:output_type -> DateTime
	1, // 4: Random.GetRandom:output_type -> RandomInt
	5, // 5: Random.GetRandomPass:output_type -> RandomPass
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protoapi_proto_init() }
func file_protoapi_proto_init() {
	if File_protoapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoapi_proto_rawDesc), len(file_protoapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protoapi_proto_goTypes,
		DependencyIndexes: file_protoapi_proto_depIdxs,
		MessageInfos:      file_protoapi_proto_msgTypes,
	}.Build()
	File_protoapi_proto = out.File
	file_protoapi_proto_goTypes = nil
	file_protoapi_proto_depIdxs = nil
}
